stages:
  preprocess:
    cmd: python src/preprocessing.py
    deps:
      - data/iris.data
      - src/preprocessing.py
    outs:
      - data/X_train.csv
      - data/X_test.csv
      - data/y_train.csv
      - data/y_test.csv
      - data/scaler.pkl